title: SBPDA  
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  GitHub: https://github.com/NBISweden/sbpda
# Navigation structure
collections:
  docs:
    output: true

# Site settings    
footer_links:
  - title: "Supported By"
    items:
      - name: "SciLifeLab"
        img: "/assets/images/SciLifeLab_Logotype_Green_POS.svg"
        url: "https://www.scilifelab.se/"
      - name: "KTH"
        img: "/assets/images/KTH_Royal_Institute_of_Technology_logo.png"
        url: "https://www.kth.se/"
      - name: "Stockholm University"
        img: "/assets/images/Stockholm_University.png"
        url: "https://www.su.se/"
